title: ZALF AR Cookbook App
logo: /assets/img/logo_120x120.jpg
description: Documentation for the ZALF AR Cookbook app, created by students of Filmuniversität Bablesberg.
show_downloads: false
google_analytics:
theme: jekyll-theme-minimal
